### ISSUE TITLE
Installation is Broken

### ISSUE THREAD

**Issue by Ovewh** [duncanwp/ESEm#30]
Hi 

I'm not able to install ESEm via pip and because it cannot find compatible version of tensorflow. I believe that requirement are to loosely specified. However it is essentially impossible for me to guess which version of tensorflow, numpy, and python that is supported.

**Comment by duncanwp** [comment]
Hmm, sorry about that. Usually when building these environments it's best to start from scratch and specify everything up front. Could you show what command you're using and where it's failing to resolve?

**Comment by Ovewh** [comment]
I got it working now. In case anyone else have troubles i used the following conda environment.  And then installed ESEm locally by cloning the repo and doing a `pip install --no-deps -e ESEm`

```yaml
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - antlr-python-runtime=4.7.2
  - argon2-cffi=21.1.0
  - asttokens=2.0.5
  - attrs=23.2.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=6.1.0
  - bottleneck=1.3.5
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.11.17
  - cartopy=0.22.0
  - certifi=2023.11.17
  - cf-units=3.2.0
  - cffi=1.16.0
  - cftime=1.6.2
  - cis=1.7.9
  - click=8.1.7
  - cloudpickle=3.0.0
  - comm=0.1.2
  - contourpy=1.2.0
  - curl=8.5.0
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dask-core=2024.1.0
  - dbus=1.13.18
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.0.4
  - executing=0.8.3
  - expat=2.5.0
  - fontconfig=2.14.2
  - fonttools=4.47.2
  - freetype=2.12.1
  - fsspec=2023.12.2
  - geos=3.12.1
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.78.3
  - glib-tools=2.78.3
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - hdf4=4.2.15
  - hdf5=1.12.1
  - icu=73.2
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - importlib_resources=6.1.1
  - intel-openmp=2023.1.0
  - ipykernel=6.25.0
  - ipython=8.15.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.3
  - iris=3.7.0
  - jedi=0.18.1
  - jinja2=3.1.3
  - jpeg=9e
  - jsonschema=4.20.0
  - jsonschema-specifications=2023.12.1
  - jupyter=1.0.0
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.5.0
  - jupyterlab_pygments=0.3.0
  - jupyterlab_widgets=3.0.9
  - kiwisolver=1.4.5
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libclang13=14.0.6
  - libcups=2.3.3
  - libcurl=8.5.0
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.3
  - libiconv=1.17
  - libllvm14=14.0.6
  - libnetcdf=4.8.1
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libpq=12.15
  - libsodium=1.0.18
  - libsqlite=3.44.2
  - libssh2=1.10.0
  - libstdcxx-ng=13.2.0
  - libtiff=4.5.1
  - libudunits2=2.2.28
  - libuuid=2.38.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.6.0
  - libxml2=2.12.4
  - libzip=1.8.0
  - libzlib=1.2.13
  - llvm-openmp=17.0.6
  - locket=1.0.0
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - mistune=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - munkres=1.1.4
  - mysql=5.7.24
  - nbclient=0.8.0
  - nbconvert=7.14.1
  - nbconvert-core=7.14.1
  - nbconvert-pandoc=7.14.1
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - netcdf4=1.6.2
  - notebook=6.3.0
  - numexpr=2.8.7
  - numpy=1.26.3
  - numpy-base=1.26.3
  - openjpeg=2.5.0
  - openssl=3.2.0
  - packaging=23.1
  - pandas=2.1.4
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.4.1
  - pcre2=10.42
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - ply=3.11
  - proj=9.3.0
  - prometheus_client=0.19.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyhdf=0.11.3
  - pyproj=3.6.1
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pyshp=2.3.1
  - python=3.9.18
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.19.1
  - python-tzdata=2023.3
  - python-xxhash=3.4.1
  - python_abi=3.9
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - pyzmq=25.1.0
  - qt-main=5.15.2
  - qtconsole-base=5.5.1
  - qtpy=2.4.1
  - readline=8.2
  - referencing=0.32.1
  - rpds-py=0.10.6
  - scipy=1.11.4
  - send2trash=1.8.2
  - setuptools=68.2.2
  - shapely=2.0.2
  - sip=6.7.12
  - six=1.16.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tbb=2021.8.0
  - terminado=0.18.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.3.3
  - traitlets=5.7.1
  - typing_extensions=4.9.0
  - tzdata=2023d
  - udunits2=2.2.28
  - unicodedata2=15.1.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.41.2
  - widgetsnbextension=4.0.9
  - xarray=2023.6.0
  - xkeyboard-config=2.40
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.8.7
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xxhash=0.8.2
  - xz=5.4.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.0.0
      - astunparse==1.6.3
      - cachetools==5.3.2
      - charset-normalizer==3.3.2
      - check-shapes==1.1.1
      - deprecated==1.2.14
      - dm-tree==0.1.8
      - dropstackframe==0.1.0
      - esem==1.1.0
      - flatbuffers==23.5.26
      - gast==0.5.4
      - google-auth==2.26.2
      - google-auth-oauthlib==1.2.0
      - google-pasta==0.2.0
      - gpflow==2.9.0
      - grpcio==1.60.0
      - h5py==3.10.0
      - idna==3.6
      - ipympl==0.9.3
      - keras==2.15.0
      - lark==1.1.9
      - libclang==16.0.6
      - markdown==3.5.2
      - matplotlib==3.8.2
      - ml-dtypes==0.2.0
      - multipledispatch==1.0.0
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - pillow==10.2.0
      - protobuf==4.23.4
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pyparsing==3.1.1
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - tabulate==0.9.0
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.0.post1
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.35.0
      - tensorflow-probability==0.23.0
      - termcolor==2.4.0
      - tqdm==4.66.1
      - urllib3==2.1.0
      - werkzeug==3.0.1
      - wrapt==1.14.1


```
